# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170408_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.CharField(blank=True, default='Confidential', max_length=200, null=True),
        ),
    ]
