# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170409_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=150),
            preserve_default=False,
        ),
    ]
